apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: project-testing
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: in-cluster
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: customer2
    spec:
      project: customer1
      source:
        repoURL: https://github.com/HumayunNasir22/argo-test.git
        targetRevision: HEAD
        path: manifest
      destination:
        server: '{{url}}'
        namespace: argocd
