apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: customer1
  namespace: argocd
spec:
  sourceRepos:
    - '*'

  destinations:
    - server: https://kubernetes.default.svc
      namespace: '*'
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
  roles:
    - name: default
      policies:
        - p, proj:my-project, applications, sync, allow
    - name: read-only
      policies:
        - p, proj:my-project, applications, get, allow
